#include "rn_resolv_conf.h"

#include <stdio.h>
#include <string.h>

#define GUARD_BYTE 0x5a

/* A Tailscale-managed resolv.conf: the shape that made nginx refuse to start. */
static const char RESOLV_CONF[] =
    "# Generated by tailscaled\n"
    "nameserver fd7a:115c:a1e0::53\n"
    "nameserver 100.100.100.100\n"
    "nameserver fe80::1%en0\n"
    "search tail0a1b2.ts.net\n"
    "options ndots:0\n";

static const char *const RESOLV_CONF_NAMES[] = {
    "[fd7a:115c:a1e0::53]",
    "100.100.100.100",
};

static int failures;

static void
fail(const char *message)
{
    fprintf(stderr, "FAIL %s\n", message);
    failures++;
}

static void
expect(const char *line, rn_resolv_nameserver_t want_kind,
    const char *want_text, const char *message)
{
    char                    out[RN_RESOLV_NAMESERVER_MAX];
    size_t                  out_len;
    rn_resolv_nameserver_t  kind;

    memset(out, GUARD_BYTE, sizeof(out));
    out_len = sizeof(out);
    kind = rn_resolv_conf_nameserver(line, strlen(line), out, sizeof(out),
        &out_len);
    if (kind != want_kind) {
        fprintf(stderr, "FAIL %s: kind %d, wanted %d\n", message, (int) kind,
            (int) want_kind);
        failures++;
        return;
    }
    if (strcmp(out, want_text) != 0) {
        fprintf(stderr, "FAIL %s: got \"%s\", wanted \"%s\"\n", message, out,
            want_text);
        failures++;
        return;
    }
    if (out_len != strlen(want_text)) {
        fprintf(stderr, "FAIL %s: length %zu, wanted %zu\n", message, out_len,
            strlen(want_text));
        failures++;
    }
}

static void
check_output_capacity(void)
{
    static const char line[] = "nameserver 2001:db8::7\n";
    char              out[8];
    size_t            out_len;

    memset(out, GUARD_BYTE, sizeof(out));
    if (rn_resolv_conf_nameserver(line, strlen(line), out, sizeof(out) - 1,
            &out_len)
        != RN_RESOLV_NAMESERVER_UNUSABLE)
    {
        fail("an address larger than the output buffer was accepted");
        return;
    }
    if (out[sizeof(out) - 1] != (char) GUARD_BYTE) {
        fail("a rejected address was written past the output capacity");
        return;
    }
    if (out_len != sizeof(out) - 2 || strlen(out) != out_len) {
        fail("a rejected address was not reported as a bounded string");
    }
}

static void
check_rejected_arguments(void)
{
    static const char line[] = "nameserver ::1\n";
    char              out[RN_RESOLV_NAMESERVER_MAX];
    size_t            out_len;

    if (rn_resolv_conf_nameserver(NULL, 0, out, sizeof(out), &out_len)
            != RN_RESOLV_NAMESERVER_NONE
        || rn_resolv_conf_nameserver(line, strlen(line), NULL, sizeof(out),
            &out_len) != RN_RESOLV_NAMESERVER_NONE
        || rn_resolv_conf_nameserver(line, strlen(line), out, 0, &out_len)
            != RN_RESOLV_NAMESERVER_NONE
        || rn_resolv_conf_nameserver(line, strlen(line), out, sizeof(out), NULL)
            != RN_RESOLV_NAMESERVER_NONE)
    {
        fail("a missing line, output buffer, or length was accepted");
    }
}

/* Walk the fixture the way the module walks fgets() output. */
static void
check_resolv_conf_fixture(void)
{
    char                    collected[4][RN_RESOLV_NAMESERVER_MAX];
    const char             *line;
    const char             *end;
    size_t                  count;
    size_t                  out_len;
    size_t                  i;
    rn_resolv_nameserver_t  kind;

    count = 0;
    line = RESOLV_CONF;
    while (*line != '\0') {
        end = strchr(line, '\n');
        end = end == NULL ? line + strlen(line) : end + 1;
        if (count == sizeof(collected) / sizeof(collected[0])) {
            fail("the fixture produced more nameservers than nginx can use");
            return;
        }
        kind = rn_resolv_conf_nameserver(line, (size_t) (end - line),
            collected[count], sizeof(collected[count]), &out_len);
        if (kind == RN_RESOLV_NAMESERVER_INET
            || kind == RN_RESOLV_NAMESERVER_INET6)
        {
            count++;
        }
        line = end;
    }

    if (count != sizeof(RESOLV_CONF_NAMES) / sizeof(RESOLV_CONF_NAMES[0])) {
        fprintf(stderr, "FAIL the fixture yielded %zu nameservers, wanted %zu\n",
            count, sizeof(RESOLV_CONF_NAMES) / sizeof(RESOLV_CONF_NAMES[0]));
        failures++;
        return;
    }
    for (i = 0; i < count; i++) {
        if (strcmp(collected[i], RESOLV_CONF_NAMES[i]) != 0) {
            fprintf(stderr, "FAIL fixture nameserver %zu is \"%s\", wanted "
                "\"%s\"\n", i, collected[i], RESOLV_CONF_NAMES[i]);
            failures++;
        }
    }
}

int
main(void)
{
    /* The reported failure: a bare IPv6 nameserver is read as host:port. */
    expect("nameserver fd7a:115c:a1e0::53\n", RN_RESOLV_NAMESERVER_INET6,
        "[fd7a:115c:a1e0::53]", "an IPv6 nameserver was not bracketed");
    expect("nameserver ::1\n", RN_RESOLV_NAMESERVER_INET6, "[::1]",
        "a loopback IPv6 nameserver was not bracketed");
    expect("nameserver ::ffff:192.0.2.1\r\n", RN_RESOLV_NAMESERVER_INET6,
        "[::ffff:192.0.2.1]", "an IPv4-mapped nameserver was not bracketed");
    expect("\tnameserver\t2001:db8::1 # comment\n", RN_RESOLV_NAMESERVER_INET6,
        "[2001:db8::1]", "indentation or a trailing comment was kept");
    expect("nameserver 2001:db8::2;comment\n", RN_RESOLV_NAMESERVER_INET6,
        "[2001:db8::2]", "a semicolon comment was kept");
    expect("nameserver [2001:db8::3]\n", RN_RESOLV_NAMESERVER_INET6,
        "[2001:db8::3]", "a bracketed IPv6 nameserver was bracketed again");

    /* Everything nginx already accepted must survive unchanged. */
    expect("nameserver 1.1.1.1\n", RN_RESOLV_NAMESERVER_INET, "1.1.1.1",
        "an IPv4 nameserver was not copied verbatim");
    expect("nameserver 127.0.0.53 # systemd-resolved\n",
        RN_RESOLV_NAMESERVER_INET, "127.0.0.53",
        "a commented IPv4 nameserver was not copied verbatim");
    expect("nameserver dns.example.invalid\n", RN_RESOLV_NAMESERVER_INET,
        "dns.example.invalid", "a nameserver host name was not preserved");

    /* Lines that are not nameserver directives. */
    expect("", RN_RESOLV_NAMESERVER_NONE, "", "an empty line was accepted");
    expect("search example.invalid\n", RN_RESOLV_NAMESERVER_NONE, "",
        "a search line was read as a nameserver");
    expect("options ndots:2\n", RN_RESOLV_NAMESERVER_NONE, "",
        "an options line was read as a nameserver");
    expect("# nameserver 2001:db8::4\n", RN_RESOLV_NAMESERVER_NONE, "",
        "a commented-out nameserver was read as a nameserver");
    expect("nameserverfoo 2001:db8::5\n", RN_RESOLV_NAMESERVER_NONE, "",
        "an unknown directive starting with nameserver was accepted");

    /* Nameservers nginx cannot parse are reported, never passed through. */
    expect("nameserver fe80::1%en0\n", RN_RESOLV_NAMESERVER_UNUSABLE,
        "fe80::1%en0", "a zone-scoped nameserver was accepted");
    expect("nameserver [2001:db8::6\n", RN_RESOLV_NAMESERVER_UNUSABLE,
        "[2001:db8::6", "an unterminated bracket was accepted");
    expect("nameserver\n", RN_RESOLV_NAMESERVER_UNUSABLE, "",
        "a nameserver line without an address was accepted");
    expect("nameserver \n", RN_RESOLV_NAMESERVER_UNUSABLE, "",
        "a blank nameserver address was accepted");

    check_output_capacity();
    check_rejected_arguments();
    check_resolv_conf_fixture();

    if (failures != 0) {
        return 1;
    }
    puts("PASS resolv.conf nameservers become valid nginx resolver arguments");
    return 0;
}
